name: Build Kivy APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip git zip unzip openjdk-17-jdk wget
        pip install buildozer cython

    - name: Install Android SDK + NDK
      run: |
        mkdir -p $HOME/android
        cd $HOME/android
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip
        mkdir -p $HOME/android/cmdline-tools
        mv cmdline-tools $HOME/android/cmdline-tools/latest

        # Add to PATH
        echo "export ANDROID_HOME=$HOME/android" >> $GITHUB_ENV
        echo "export PATH=$HOME/android/cmdline-tools/latest/bin:$HOME/android/platform-tools:$HOME/android/emulator:$PATH" >> $GITHUB_ENV

        # Install required SDK packages
        yes | $HOME/android/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android "platform-tools" "platforms;android-31" "build-tools;31.0.0" "ndk;21.4.7075529"

    - name: Build APK
      run: |
        buildozer init || true
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: kivy-app
        path: bin/*.apk
