name: Build Kivy APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip git zip unzip openjdk-17-jdk wget
        pip install buildozer cython

    - name: Install Android SDK + NDK
      run: |
        mkdir -p $HOME/.buildozer/android/platform
        cd $HOME/.buildozer/android/platform
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d cmdline-tools
        mv cmdline-tools/cmdline-tools $HOME/.buildozer/android/platform/cmdline-tools

        echo "ANDROID_HOME=$HOME/.buildozer/android/platform" >> $GITHUB_ENV
        echo "PATH=$HOME/.buildozer/android/platform/cmdline-tools/bin:$HOME/.buildozer/android/platform/platform-tools:$PATH" >> $GITHUB_ENV

        yes | $HOME/.buildozer/android/platform/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform "platform-tools" "platforms;android-31" "build-tools;31.0.0" "ndk;21.4.7075529"

    - name: Build APK
      run: |
        buildozer init || true
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: kivy-app
        path: bin/*.apk
